[tool.poetry]
name = "pydantic-plus"
version = "1.1.1.post0"
description = """\
Pydantic BaseModel extended a bit:
  - PurePosixPath json encoding and validation
  - from_toml and from_tomls classmethods
"""
authors = ["Randall Pittman <randallpittman@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.8.1"
rtoml = "^0.7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipython = "^7.22.0"
isort = "^5.8.0"
black = "^21.4b2"

[build-system]
requires = ["poetry-core>=1.0.0", "tomli"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 109
target-version = ['py38']

[tool.isort]
line_length = 109
multi_line_output = 3
include_trailing_comma = true
